# Generated by Django 2.2.24 on 2021-11-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='ans', to='app.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='person_que',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='person_que', to='app.Profile'),
        ),
    ]
