# Generated by Django 2.2.24 on 2021-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211106_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like_que',
            field=models.ManyToManyField(related_name='like_que', to='app.LikeToQue'),
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='app.Tag'),
        ),
    ]
