# Generated by Django 2.2.24 on 2021-11-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211106_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='like_ans',
            field=models.ManyToManyField(related_name='like_ans', to='app.LikeToAns'),
        ),
        migrations.AddField(
            model_name='answer',
            name='person_ans',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='person_ans', to='app.Profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='que',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='que', to='app.Question'),
        ),
    ]
