# Generated by Django 2.2.24 on 2021-11-06 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211106_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='like_ans',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='like_que',
        ),
        migrations.AddField(
            model_name='answer',
            name='like_ans',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='like_ans', to='app.LikeToAns'),
        ),
        migrations.AddField(
            model_name='liketoans',
            name='person_anslike',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='person_anslike', to='app.Profile'),
        ),
        migrations.AddField(
            model_name='liketoque',
            name='person_quelike',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='person_quelike', to='app.Profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='like_que',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='like_que', to='app.LikeToQue'),
        ),
    ]
