# Generated by Django 2.2.24 on 2021-11-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211106_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='person_que',
        ),
    ]
