# Generated by Django 2.2.24 on 2021-11-07 19:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211107_1602'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='liketoque',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
