# Generated by Django 2.2.24 on 2021-11-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211107_1935'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='liketoque',
            managers=[
            ],
        ),
    ]
