# Generated by Django 2.2.24 on 2021-11-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
