# Generated by Django 2.2.24 on 2021-11-23 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_profile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default='', on_delete=None, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
