# Generated by Django 2.2.24 on 2022-01-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20220104_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rate',
        ),
    ]
