# Generated by Django 2.2.24 on 2022-01-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_question_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='person_ans',
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='que',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.Question'),
        ),
    ]
