# Generated by Django 2.2.24 on 2022-01-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220104_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='rating',
        ),
        migrations.AddField(
            model_name='liketoque',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='liketoque',
            name='like_que',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like', to='app.Question'),
        ),
    ]
