# Generated by Django 2.2.24 on 2022-01-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20220104_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='liketoans',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
