# Generated by Django 2.2.24 on 2022-01-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_liketoans_is_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketoque',
            name='person_like_que',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like', to='app.Profile'),
        ),
    ]
