# Generated by Django 2.2.24 on 2022-01-06 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20220105_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='liketoans',
            name='person_like_ans',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like_ans', to='app.Profile'),
        ),
    ]
