# Generated by Django 2.2.24 on 2022-01-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20220106_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liketoque',
            name='like_que',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like_que', to='app.Question'),
        ),
        migrations.AlterField(
            model_name='liketoque',
            name='person_like_que',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='like_que', to='app.Profile'),
        ),
    ]
